[workspace]
authors = ["Cyris Kissane <cyris.kissane@gmail.com>"]
channels = ["conda-forge"]
name = "poke2emon"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"
